### ISSUE TITLE
Release 1.0.22 gives ImportError: no module named `skimage`

### ISSUE THREAD

**Issue by lebrice** [Continvvm/continuum#141]
```python3
from torch.utils.data import DataLoader

from continuum import ClassIncremental
from continuum.datasets import MNIST
from continuum.tasks import split_train_val

dataset = MNIST("my/data/path", download=True, train=True)
scenario = ClassIncremental(
    dataset,
    increment=1,
    initial_increment=5
)

print(f"Number of classes: {scenario.nb_classes}.")
print(f"Number of tasks: {scenario.nb_tasks}.")

for task_id, train_taskset in enumerate(scenario):
    train_taskset, val_taskset = split_train_val(train_taskset, val_split=0.1)
    train_loader = DataLoader(train_taskset, batch_size=32, shuffle=True)
    val_loader = DataLoader(val_taskset, batch_size=32, shuffle=True)

    for x, y, t in train_loader:
        pass
        # Do your cool stuff here
```
Gives:
```console
$> python foo.py 
Traceback (most recent call last):
  File "foo.py", line 3, in <module>
    from continuum import ClassIncremental
  File "/home/fabrice/repos/continuum/continuum/__init__.py", line 10, in <module>
    from continuum import datasets
  File "/home/fabrice/repos/continuum/continuum/datasets/__init__.py", line 19, in <module>
    from continuum.datasets.ctrl import CTRL, CTRLplus, CTRLminus, CTRLin, CTRLout, CTRLplastic
  File "/home/fabrice/repos/continuum/continuum/datasets/ctrl.py", line 4, in <module>
    from skimage.transform import resize
ModuleNotFoundError: No module named 'skimage'
```

**Comment by arthurdouillard** [comment]
Fixed in 1.0.23, thanks!
