### ISSUE TITLE
Example code from README doesn't work (?)

### ISSUE THREAD

**Issue by lebrice** [Continvvm/continuum#32]
When trying to run the example code, I get the following error:

```
from torch.utils.data import DataLoader

from continuum import ClassIncremental, split_train_val
from continuum.datasets import MNIST

clloader = ClassIncremental(
    MNIST("my/data/path", download=True),
    increment=1,
    initial_increment=5,
    train=True  # a different loader for test
)

print(f"Number of classes: {clloader.nb_classes}.")
print(f"Number of tasks: {clloader.nb_tasks}.")

for task_id, train_dataset in enumerate(clloader):
    train_dataset, val_dataset = split_train_val(train_dataset, val_split=0.1)
    train_loader = DataLoader(train_dataset)
    val_loader = DataLoader(val_dataset)
    for x, y in train_loader:
        print("Never gets here?")
        exit()
    # Do your cool stuff here
```

```
Number of classes: 10.
Number of tasks: 6.
Traceback (most recent call last):
  File "foo.py", line 20, in <module>
    for x, y in train_loader:
  File "/home/fabrice/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/fabrice/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/fabrice/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/fabrice/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/fabrice/Source/SSCL/utils/continuum/continuum/task_set.py", line 96, in __getitem__
    t = self.t[index]
TypeError: 'Compose' object does not support indexing
```

**Comment by lebrice** [comment]
Bug seems to come from train_val_split, lines 120-121:
```
    train_dataset = TaskSet(x[train_indexes], y[train_indexes], dataset.trsf, dataset.data_type)
    val_dataset = TaskSet(x[val_indexes], y[val_indexes], dataset.trsf, dataset.data_type)
```
As the arg `t` isn't passed, it gets the value of `Compose` from `dataset.trsf`. I don't quite know how to supply the `t` array for now, so that's as much as I can help for now.

**Comment by arthurdouillard** [comment]
Indeed you're right, the `split_train_val` function was bugged as it forgot the task id `t`.

I've fixed and added a test so it doesn't happen again.

Btw, beware that your loader gives you a tuple of three and not two elements:
```
for x, y, t in train_loader:
        # Do your cool stuff here
```

`t` represents the task id associated to the sample (you're free to not use it of course). It is useful when slicing loaders and taking several tasks together (like `clloader[:8]`).

Sorry for the inconvenience and thanks for the report :)
