### ISSUE TITLE
you pip installation command installs a wrong version with an error!

### ISSUE THREAD

**Issue by mmderakhshani** [Continvvm/continuum#55]
Traceback (most recent call last):
  File "main_cl_cifar10_100_scl_prototype_inference_end_to_end.py", line 23, in <module>
    from continuum.task_set import split_train_val
  File "/home/mohammad/.local/lib/python3.6/site-packages/continuum/task_set.py", line 8, in <module>
    from continuum.viz import plot
ImportError: cannot import name 'plot'

**Comment by arthurdouillard** [comment]
Hum I'm not sure why there is both a `task_set` in `continuum` and in `continuum/tasks`...

I'm trying to fix it.

**Comment by mmderakhshani** [comment]
Ok. let me check.
